export const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';

export const TOGGLE_PAGE = 'TOGGLE_PAGE';

export const TOGGLE_SEARCHBAR = 'OPEN_SEARCHBAR';
export const EDIT_SEARCHBAR = 'EDIT_SEARCHBAR';